name: httpserver
description: Small HttpServer app in Dart
homepage: https://github.com/x-hgg-x/httpserver

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http_server: ^0.9.6
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
